### ISSUE TITLE
Async options in select are not reflected

### ISSUE THREAD

**Issue by shindekaps** [sherweb/ng2-materialize#88] opened 2017-03-30 13:53 UTC
Ng for not working for select component

**Comment by jfcere** [comment] 2017-03-30 14:30
Hi @shindekaps,

We had this issue previously but it is supposed to be fixed in v1.2.0. Here is a quick example ...

```html
<mz-select-container>
  <select mz-select
    id="select-country"
    [label]="'Country'"
    [placeholder]="'Choose your country'">
    <option *ngFor="let country of countries" [selected]="country === user.country" [ngValue]="country">{{ country.name }}</option>
  </select>
</mz-select-container>
```

If you have updated to v1.2.0 and still have the problem can you provide a sample of your code?

Thanks,

**Comment by shindekaps** [comment] 2017-03-31 04:57
Hi,
*ngFor is working when data is hard coded. When the data is coming asynchronous then it not working. Also I got workaround when we use ngIf then it is working.
E.g.
  `   <mz-select-container>
  <select mz-select
    id="select-number"
    [label]="'Number'"
    [placeholder]="'Choose a number'"
    [(ngModel)]="optionValue">
    <option *ngFor="let option of comapnyList" [selected]="option === optionValue">{{ option }}</option>
  </select>
</mz-select-container>`

where companyList is coming from server.Above example is not working. But when we add *ngIf then it is working
E.g.
  `   <mz-select-container *ngIf="comapnyList.length>0">
  <select mz-select
    id="select-number"
    [label]="'Number'"
    [placeholder]="'Choose a number'"
    [(ngModel)]="optionValue">
    <option *ngFor="let option of comapnyList" [selected]="option === optionValue">{{ option }}</option>
  </select>
</mz-select-container>`

Thanks
Kapil Shinde

**Comment by charpeni** [comment] 2017-04-03 18:31
Thank you for the reporting, you're right there're bugs with async options.

We're on it.

**Closed** 2017-04-10 15:34 UTC
Labels: bug

**Comment by charpeni** [comment] 2017-04-10 15:40
@shindekaps it should be fixed by #91 and it will be released to npm in the next days/weeks.

If there is anything else or if the issue is not properly fixed, feel free to ping us.
