### ISSUE TITLE
ngFor MzCollectionItemComponent Issue

### ISSUE THREAD

**Issue by bakoserge** [sherweb/ng2-materialize#155] opened 2017-07-06 15:16 UTC
Hi ,
I am having some issue with the mz-collection .
when I first load the application with the schedules array set the dom is rendered with no issue, but when I add a new item to the schedules array, I get this error .
Can you please help.
Thanks.

--ERROR--
ERROR TypeError: Cannot read property 'insertBefore' of null
    at MzCollectionItemComponent.webpackJsonp.../../../../ng2-materialize/dist/shared/remove-component-host/remove-component-host.js.MzRemoveComponentHost.ngAfterViewInit (remove-component-host.js:11)
    at callProviderLifecycles (core.es5.js:11269)
    at callElementProvidersLifecycles (core.es5.js:11244)
    at callLifecycleHooksChildrenFirst (core.es5.js:11228)
    at checkAndUpdateView (core.es5.js:12325)
    at callViewAction (core.es5.js:12680)
    at execEmbeddedViewsAction (core.es5.js:12638)
    at checkAndUpdateView (core.es5.js:12318)
    at callViewAction (core.es5.js:12680)
    at execEmbeddedViewsAction (core.es5.js:12638)

----SAMPLE CODE USED----

`<div *ngIf="schedules">
                    <mz-collection>
                        <mz-collection-item *ngFor="let app of schedules;">
                            <div class="row" style="margin-bottom:0px">
                                <div class="col s4 m4" style="border-right: 2px #337ab7 solid;">
                                    <div>
                                        {{app.startDate | date: 'HH:mm'}} - {{app.endDate | date: 'HH:mm'}}
                                    </div>
                                </div>
                                <div class="col s8 m8">
                                    <div>
                                        {{app.clientName}}
                                    </div>
                                </div>
                            </div>
                        </mz-collection-item>
                    </mz-collection>
                </div>
`

**Comment by jfcere** [comment] 2017-07-06 15:27
Hi @bakoserge,

This is a duplicate of #144 where DOM manipulation for `mz-collection` (add/remove) would give the error you mentioned.

This as been fixed in master branch and will be release in [1.5.0](https://github.com/sherweb/ng2-materialize/milestone/1). We are finalizing the validation module for reactive form validation which is taking more time than we thought.

As a workaround while waiting for the new release you can still pull on master branch.

**Comment by bakoserge** [comment] 2017-07-06 15:52
Hi @jfcere ,
Thanks for the quick reply.
It will probably be better to wait for the release as i am installing it in my application using node. 
What do you think?

**Comment by jfcere** [comment] 2017-07-06 17:42
You can just replace the version of ng2-materialize in your `package.json` for this line and run `npm install` and change it back once we release.

###### package.json
```json
"ng2-materialize": "git://github.com/sherweb/ng2-materialize.git#master"
```

**Comment by jfcere** [comment] 2017-07-06 21:06
Closing the issue, feel free to reopen if there is anything.

**Closed by jfcere** 2017-07-06 21:06 UTC
Labels: Duplicate
