### ISSUE TITLE
modal window is as dim as the background. cannot get to the modal CSS at dev tools. 

### ISSUE THREAD

**Issue by halukkaramete** [sherweb/ng2-materialize#283] opened 2018-02-04 21:01 UTC
When asking general "how to" questions:

- Please do not open an issue here!
- Instead, ask for help on [StackOverflow](https://stackoverflow.com/) with Materialize and Angular tags.

- Read the [CONTRIBUTING document](https://github.com/sherweb/ng2-materialize/blob/master/CONTRIBUTING.md) Any issues that are violating the contributing guidelines, will be closed!
- [Search for duplicate or closed issues](https://github.com/sherweb/ng2-materialize/issues?utf8=%E2%9C%93&q=is%3Aissue) and make sure that is not an issue related to Materialize or other library.
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs.
- Provide a [StackBlitz](https://stackblitz.com/edit/ngx-materialize) that reproduce your issue.

## Steps to Reproduce (for bugs)

1. http://startalkcreate.org/lpgTemp/learning-plan/view-detail/862
2.click on the green modal button
3.the problem is obvious.
4.

## Your Environment

* Version used:
* Angular version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project (if appropriate):

**Comment by LiadIdan** [comment] 2018-02-04 23:31
@halukkaramete the cause of your problem is the layout of your elements. right now your modal have two parent elements `.mat-drawer-content, .mat-drawer-container` with `z-index: 1` declaration. 
Note that the `z-index` property is relative to the parent, so the current result is expected behavior.
To fix the issue, you can remove the `z-index` property from the parent elements or set it to `initial.`

**Comment by halukkaramete** [comment] 2018-02-05 04:26
This is an amazing insight Liad.
*I cannot thank you enough. *

I updated the demo link per your suggestion and as you see (
http://startalkcreate.org/lpgTemp/learning-plan/view-detail/862 ), it NOW
works like a charm!

However, I got 2 questions!

1) *how did you figure out about those parent elements
(.mat-drawer-content, .mat-drawer-container) with z-index issues? *

*  Is there a technique to search in dev-tools that can list a z-index
chain for a given element? *

2) why does not the second placement of the button MODAL-2,  (the one
within tabs ) does NOT work?
*Please note that I applied the teachings from your first solution for the
modal 2 and added these CSS but that did not make a diff. *

mat-tab-group {
>   z-index:initial !important;
> }
> .demo-tab-group {
>   z-index:initial !important;
> }
> mat-tab{
>   z-index:initial !important;
> }


Would you please be so kind enough to take a look at what the problem is
with MODAL-2 use-case?
Since I do not know the answer to my 1st question ( *the one in purple*),
my hands are still tight.

Thank you  again
haluk

**Comment by LiadIdan** [comment] 2018-02-05 14:44
@halukkaramete I'm happy I could help you :wink:

In answer to your questions:
1. Open the chrome dev tools and inside the **Elements** panel you can search for a specific element by pressing <kbd>Ctrl</kbd> + <kbd>F</kbd> in your case I've looked for the `mz-modal` element. Once you've found the element, you can traverse up through its parents in the DOM tree and inspect their applied CSS rules in the **Computed** tab. To make it more simple, you can use the **Filter** text box to look for a specific property or value such as `z-index` in your case. Check the **Styles** tab to determine where the rule is coming from.
2. As before you have parent element `.mat-tab-body.mat-tab-body-active` with `z-index: 1` declaration.

**Comment by halukkaramete** [comment] 2018-02-05 17:36
Superior help.
One of the best I have recently received.

Thank you.

**Comment by jfcere** [comment] 2018-02-21 00:08
Thanks for your follow up @LiadIdan, I am closing the issue.

**Closed by jfcere** 2018-02-21 00:08 UTC
Labels: Question
